// WEB-INC-008 (ML-DEVOS-RFC-005 / ML-DEVOS-AS-017 / D-026) append-only
// audit substrate tests. Every database used here is a local
// Wrangler/Miniflare D1 simulation (`getPlatformProxy({ remoteBindings:
// false })`) persisted to a throwaway temp directory per test — no test in
// this file can reach a real Cloudflare resource (AS17-F012).
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { getPlatformProxy } from "wrangler";
import { applyCurrentSchema, CURRENT_PRODUCT_TABLE_NAMES } from "../worker/d1/schema.mjs";
import { validateAuditEvent, appendAuditEvent } from "../worker/d1/audit.mjs";
import { buildDashboardPayload } from "../worker/admin/dashboard.mjs";

const WRANGLER_CONFIG_PATH = path.join(import.meta.dirname, "..", "wrangler.jsonc");

async function openTestDb() {
  const statePath = fs.mkdtempSync(path.join(os.tmpdir(), "web-inc-008-d1-test-"));
  const proxy = await getPlatformProxy({
    configPath: WRANGLER_CONFIG_PATH,
    persist: { path: statePath },
    remoteBindings: false,
  });
  await applyCurrentSchema(proxy.env.DB);
  return {
    db: proxy.env.DB,
    async cleanup() {
      await proxy.dispose();
      fs.rmSync(statePath, { recursive: true, force: true });
    },
  };
}

function validEvent(overrides = {}) {
  return {
    actor: "builder:web-inc-008-test",
    action: "audit_substrate_proof",
    entityType: "project",
    entityId: "project-fixture",
    revisionId: 1,
    result: "success",
    ...overrides,
  };
}

async function countAuditRows(db) {
  const row = await db.prepare("SELECT COUNT(*) AS n FROM audit_log").first();
  return row.n;
}

// --- AS17-F002: exactly 15 tables after the current (0001 + 0002) schema ---

test("applying the current schema (0001 + 0002) creates exactly the 15 authorized tables, including audit_log", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    const result = await db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").all();
    const tables = result.results
      .map(row => row.name)
      .filter(name => !name.startsWith("_cf_") && !name.startsWith("sqlite_") && name !== "d1_migrations");
    assert.equal(tables.length, 15);
    assert.deepEqual(tables, [...CURRENT_PRODUCT_TABLE_NAMES].sort());
    assert.ok(tables.includes("audit_log"));
  } finally {
    await cleanup();
  }
});

// --- valid append: success and failure rows persist exactly as given ---

test("appendAuditEvent persists a valid success event", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    await appendAuditEvent(db, validEvent({ result: "success" }));
    const row = await db.prepare("SELECT * FROM audit_log").first();
    assert.equal(row.actor, "builder:web-inc-008-test");
    assert.equal(row.action, "audit_substrate_proof");
    assert.equal(row.entity_type, "project");
    assert.equal(row.entity_id, "project-fixture");
    assert.equal(row.revision_id, 1);
    assert.equal(row.result, "success");
    assert.ok(typeof row.occurred_at === "string" && row.occurred_at.length > 0);
    assert.ok(Number.isInteger(row.id));
  } finally {
    await cleanup();
  }
});

test("appendAuditEvent persists a valid failure event and never transforms it to success", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    await appendAuditEvent(db, validEvent({ result: "failure", revisionId: null }));
    const row = await db.prepare("SELECT * FROM audit_log").first();
    assert.equal(row.result, "failure");
    assert.equal(row.revision_id, null);
  } finally {
    await cleanup();
  }
});

test("occurred_at is generated by the writer itself, not accepted from the caller", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    const before = new Date();
    await appendAuditEvent(db, { ...validEvent(), occurredAt: "1999-01-01T00:00:00.000Z" }).catch(() => {});
    // The above call should have been rejected entirely (unknown field), so
    // no row should exist yet.
    assert.equal(await countAuditRows(db), 0);

    await appendAuditEvent(db, validEvent());
    const row = await db.prepare("SELECT * FROM audit_log").first();
    const occurredAt = new Date(row.occurred_at);
    assert.ok(occurredAt.getTime() >= before.getTime() - 1000);
  } finally {
    await cleanup();
  }
});

// --- validation rejection: each case writes zero rows ---

test("validateAuditEvent and appendAuditEvent reject an unknown field", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    assert.throws(() => validateAuditEvent(validEvent({ extra: "not-allowed" })), /unknown field/);
    await assert.rejects(() => appendAuditEvent(db, validEvent({ extra: "not-allowed" })), /unknown field/);
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

test("validateAuditEvent and appendAuditEvent reject an invalid actor", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    const tooLong = "a".repeat(101);
    for (const badActor of ["", tooLong, "line\nbreak", 12345, null]) {
      assert.throws(() => validateAuditEvent(validEvent({ actor: badActor })), /actor/);
      await assert.rejects(() => appendAuditEvent(db, validEvent({ actor: badActor })));
    }
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

test("validateAuditEvent and appendAuditEvent reject an invalid action/entityType", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    for (const bad of ["Has-Upper-Case", "has space", "", "a".repeat(81), "1-starts-with-digit"]) {
      assert.throws(() => validateAuditEvent(validEvent({ action: bad })), /action/);
      assert.throws(() => validateAuditEvent(validEvent({ entityType: bad })), /entityType/);
    }
    await assert.rejects(() => appendAuditEvent(db, validEvent({ action: "Bad Action" })));
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

test("validateAuditEvent and appendAuditEvent reject an invalid entityId", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    for (const bad of ["", "has space", "a".repeat(201), "semi;colon"]) {
      assert.throws(() => validateAuditEvent(validEvent({ entityId: bad })), /entityId/);
    }
    await assert.rejects(() => appendAuditEvent(db, validEvent({ entityId: "" })));
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

test("validateAuditEvent and appendAuditEvent reject an invalid revisionId", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    for (const bad of [0, -1, 1.5, "1", Number.MAX_SAFE_INTEGER + 1]) {
      assert.throws(() => validateAuditEvent(validEvent({ revisionId: bad })), /revisionId/);
    }
    assert.doesNotThrow(() => validateAuditEvent(validEvent({ revisionId: null })));
    assert.doesNotThrow(() => validateAuditEvent(validEvent({ revisionId: undefined })));
    await assert.rejects(() => appendAuditEvent(db, validEvent({ revisionId: -1 })));
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

test("validateAuditEvent and appendAuditEvent reject a result that is not exactly success or failure", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    for (const bad of ["SUCCESS", "ok", "error", "", 1, null, undefined]) {
      assert.throws(() => validateAuditEvent(validEvent({ result: bad })), /result/);
    }
    await assert.rejects(() => appendAuditEvent(db, validEvent({ result: "ok" })));
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

test("the audit writer refuses to persist a JWT-shaped or oversized actor value", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    const fakeJwt =
      "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9." +
      "eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlhdCI6MTUxNjIzOTAyMn0." +
      "a".repeat(200);
    assert.throws(() => validateAuditEvent(validEvent({ actor: fakeJwt })), /actor/);
    await assert.rejects(() => appendAuditEvent(db, validEvent({ actor: fakeJwt })));
    assert.equal(await countAuditRows(db), 0);
  } finally {
    await cleanup();
  }
});

// --- AS17-F005: database-level append-only enforcement (bypassing the writer entirely) ---

test("a direct UPDATE against audit_log is rejected at the database layer", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    await appendAuditEvent(db, validEvent());
    const before = await db.prepare("SELECT * FROM audit_log").first();

    await assert.rejects(
      () => db.prepare("UPDATE audit_log SET result = 'failure' WHERE id = ?").bind(before.id).run(),
      /append-only/
    );

    const after = await db.prepare("SELECT * FROM audit_log").first();
    assert.deepEqual(after, before);
  } finally {
    await cleanup();
  }
});

test("a direct DELETE against audit_log is rejected at the database layer", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    await appendAuditEvent(db, validEvent());
    assert.equal(await countAuditRows(db), 1);

    await assert.rejects(() => db.prepare("DELETE FROM audit_log").run(), /append-only/);

    assert.equal(await countAuditRows(db), 1);
  } finally {
    await cleanup();
  }
});

// --- AS17-F007: audit INSERT failure itself must throw, never report success ---

function throwingAuditDb(message) {
  return {
    prepare() {
      return {
        bind() {
          return this;
        },
        run: () => Promise.reject(new Error(message)),
      };
    },
  };
}

test("a forced audit INSERT failure propagates/rejects and is never reported as success", async () => {
  const failingDb = throwingAuditDb("SIMULATED_D1_STORAGE_FAILURE");
  await assert.rejects(() => appendAuditEvent(failingDb, validEvent()), /SIMULATED_D1_STORAGE_FAILURE/);
});

// --- AS17-F009: no foreign key into/out of audit_log ---

test("audit_log declares no foreign key (logical references only)", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    const fkRows = (await db.prepare("PRAGMA foreign_key_list(audit_log)").all()).results;
    assert.equal(fkRows.length, 0);

    // Proves entity_id/entity_type/revision_id are logical references only:
    // an audit row referencing an entity that does not exist in any base
    // table is accepted, not rejected.
    await appendAuditEvent(db, validEvent({ entityId: "does-not-exist-anywhere", revisionId: 999999 }));
    assert.equal(await countAuditRows(db), 1);
  } finally {
    await cleanup();
  }
});

// --- AS17-F010 / D-026: WEB-INC-002 dashboard remains completely unchanged ---

test("buildDashboardPayload's output is unchanged and exposes no audit data even when audit_log has rows", async () => {
  const { db, cleanup } = await openTestDb();
  try {
    await appendAuditEvent(db, validEvent({ actor: "SHOULD_NOT_LEAK_INTO_DASHBOARD" }));
    await appendAuditEvent(db, validEvent({ result: "failure" }));

    const payload = await buildDashboardPayload(db);

    assert.deepEqual(Object.keys(payload).sort(), [
      "foundations",
      "navigation",
      "processSteps",
      "projects",
      "services",
      "sections",
      "siteSettings",
    ].sort());

    const rawText = JSON.stringify(payload);
    assert.ok(!rawText.includes("SHOULD_NOT_LEAK_INTO_DASHBOARD"));
    assert.ok(!rawText.toLowerCase().includes("audit"));
  } finally {
    await cleanup();
  }
});
